#  wamr Makefile.uk
#
#  Authors: Felipe Huici <felipe.huici@neclab.eu>
#
#
#  Copyright (c) 2019, NEC Europe Ltd., NEC Corporation. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived from
#     this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

################################################################################
# Library registration
################################################################################
$(eval $(call addlib_s,libwamr,$(CONFIG_LIBWAMR)))

################################################################################
# Sources
################################################################################
# Sept 9th commit
LIBWAMR_VERSION=WAMR-2.2.0
LIBWAMR_URL=https://github.com/bytecodealliance/wasm-micro-runtime/archive/refs/tags/$(LIBWAMR_VERSION).tar.gz

LIBWAMR_DIR=wasm-micro-runtime-$(LIBWAMR_VERSION)
LIBWAMR_PATCHDIR=$(LIBWAMR_BASE)/patches

$(eval $(call fetchas,libwamr,$(LIBWAMR_URL),$(LIBWAMR_VERSION).tar.gz))
$(eval $(call patch,libwamr,$(LIBWAMR_PATCHDIR),wasm-micro-runtime-$(LIBWAMR_VERSION)))

################################################################################
# Helpers
################################################################################
LIBWAMR_SRC=$(LIBWAMR_ORIGIN)/$(LIBWAMR_DIR)

################################################################################
# Library includes
################################################################################
CINCLUDES-$(CONFIG_LIBWAMR) += -I$(LIBWAMR_SRC)/core/iwasm/include   \
						-I$(LIBWAMR_SRC)/core/shared/platform/include \
						-I$(LIBWAMR_SRC)/core/shared/platform/include \
						-I$(LIBWAMR_SRC)/core/shared/platform/common/libc-util \
						-I$(LIBWAMR_SRC)/core/shared/platform/ego              \
						-I$(LIBWAMR_SRC)/core/shared/utils			\
						-I$(LIBWAMR_SRC)/core/shared/utils/uncommon \
						-I$(LIBWAMR_BASE)/include \


################################################################################
# Library flags
################################################################################
LIBWAMR_SUPPRESS_FLAGS += -Wno-implicit-function-declaration \
		          -Wno-sign-compare                  \
			  -Wno-pointer-to-int-cast           \
			  -Wno-unused-parameter              \
			  -Wno-int-conversion                \
			  -Wno-unused-label                  \
			  -Wno-unused-but-set-variable       \
			  -Wno-cast-function-type            \
			  -Wno-implicit-fallthrough

LIBWAMR_CFLAGS-y += -DNVALGRIND $(LIBWAMR_SUPPRESS_FLAGS) -DWASM_ENABLE_INTERP=1 -DWASM_ENABLE_AOT=1
LIBWAMR_CXXFLAGS-y += -DNVALGRIND $(LIBWAMR_SUPPRESS_FLAGS)

################################################################################
# Glue code
################################################################################
LIBWAMR_SRCS-$(CONFIG_LIBWAMR_MAIN_FUNCTION) += $(LIBWAMR_BASE)/glue.c

################################################################################
# Sources
################################################################################
#LIBWAMR_MAIN_FLAGS-y += -Dmain=wamr_main
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/products/linux/main.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/runtime/vmcore-wasm/invokeNative_general.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/runtime/vmcore-wasm/wasm_application.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/runtime/vmcore-wasm/wasm_interp.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/runtime/vmcore-wasm/wasm_loader.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/runtime/vmcore-wasm/wasm_runtime.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared-lib/mem-alloc/bh_memory.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/runtime/utils/wasm_log.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared-lib/platform/linux/bh_thread.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/runtime/utils/wasm_hashmap.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/lib/native/libc/libc_wrapper.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/runtime/utils/wasm_dlfcn.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared-lib/mem-alloc/mem_alloc.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared-lib/platform/linux/bh_platform.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/runtime/platform/zephyr/wasm_native.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/lib/native/base/base_lib_export.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/products/linux/ext_lib_export.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared-lib/mem-alloc/ems/ems_kfc.c
#LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared-lib/mem-alloc/ems/ems_alloc.c

# MINE #
LIBWAMR_MAIN_FLAGS-y += -Dmain=wamr_main
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/product-mini/platforms/linux/main.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/uncommon/bh_getopt.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/uncommon/bh_read_file.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/linux/platform_init.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/posix/posix_blocking_op.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/posix/posix_clock.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/posix/posix_file.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/posix/posix_malloc.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/posix/posix_memmap.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/posix/posix_sleep.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/posix/posix_socket.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/posix/posix_thread.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/posix/posix_time.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/platform/common/libc-util/libc_errno.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/mem-alloc/ems/ems_alloc.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/mem-alloc/ems/ems_gc.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/mem-alloc/ems/ems_hmu.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/mem-alloc/ems/ems_kfc.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/mem-alloc/mem_alloc.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/bh_assert.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/bh_bitmap.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/bh_common.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/bh_hashmap.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/bh_leb128.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/bh_list.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/bh_log.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/bh_queue.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/bh_vector.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/shared/utils/runtime_timer.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/libraries/libc-builtin/libc_builtin_wrapper.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/libraries/libc-wasi/libc_wasi_wrapper.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/blocking_op.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/random.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/str.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/wasm_application.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/wasm_blocking_op.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/wasm_c_api.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/wasm_exec_env.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/wasm_loader_common.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/wasm_memory.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/wasm_native.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/wasm_runtime_common.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/wasm_shared_memory.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/common/arch/invokeNative_em64_simd.s
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/interpreter/wasm_interp_fast.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/interpreter/wasm_loader.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/interpreter/wasm_runtime.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/aot/aot_intrinsic.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/aot/aot_loader.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/aot/aot_perf_map.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/aot/aot_runtime.c
LIBWAMR_SRCS-y += $(LIBWAMR_SRC)/core/iwasm/aot/arch/aot_reloc_x86_64.c


